Traceback (most recent call last):
  File "/apps/anaconda3/bin/jupyter-run", line 11, in <module>
    sys.exit(main())
  File "/apps/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/apps/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/apps/anaconda3/lib/python3.7/site-packages/jupyter_client/runapp.py", line 110, in start
    with open(filename) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'notebook.ipynb'
